Server:
  host: 0.0.0.0
  port: 19132
  motd: 'Dedicated LeafMCBE Server'
  version: 1.19.80
  max_players: 5
  offline: false

LeafMCBE:
  Terminal:
    debug: true
    showDate: true
    showGroup: true
    showPrompt: true
