Server:
  host: 0.0.0.0
  port: 19132
  motd: "Dedicated LeafMCBE Server"
  version: 1.19.70
  max_players: 3
LeafMCBE:
  debug: true
  showDateOnLogging: true
  doNotCrashOnError: true
World:
  gamemode: "creative" # survival / creative / adventure
  dimension: "flat" # overworld / flat / nether / end / void
  biome: "plains"
